# Generated by Django 4.0.3 on 2022-04-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
