# Generated by Django 4.0.3 on 2022-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False,unique=True)),
                ('car', models.CharField(max_length=222)),
                ('price', models.IntegerField()),
                ('first_name', models.CharField(max_length=111)),
                ('last_name', models.CharField(max_length=111)),
                ('pickup_location', models.CharField(max_length=111)),
                ('drop_location', models.CharField(max_length=111)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.DateTimeField()),
                ('email', models.CharField(max_length=111)),
                ('phone', models.IntegerField()),
                ('special', models.TextField()),
            ],
        ),
    ]
