# Generated by Django 4.0.3 on 2022-05-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
