# Generated by Django 4.0.3 on 2022-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='drop_location',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='special',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
    ]
