# Generated by Django 4.0.3 on 2022-05-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_order_drop_location_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
    ]
