# Generated by Django 4.0.3 on 2022-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1, max_length=111),
            preserve_default=False,
        ),
    ]
